source("R/read_nids_dictionary.R", encoding = "UTF-8")

df <- read_nids_dictionary("data/nids_current.csv")
stopifnot("cisdcp_disease_name" %in% colnames(df))
stopifnot(!"raw_match_name_zh" %in% colnames(df))
stopifnot(!"official_name_zh" %in% colnames(df))
stopifnot(!"report_name_zh" %in% colnames(df))
stopifnot(nrow(df) == 83)
notifiable <- df[df$is_notifiable_disease, ]
stopifnot(nrow(notifiable) == 42)
stopifnot(sum(notifiable$legal_class == "甲类") == 2)
stopifnot(sum(notifiable$legal_class == "乙类") == 29)
stopifnot(sum(notifiable$legal_class == "丙类") == 11)
stopifnot(is.integer(df$report_time_limit_hours))
stopifnot(is.logical(df$is_current))
stopifnot(is.logical(df$is_notifiable_disease))
stopifnot(sum(df$record_type == "aggregate") == 1)
stopifnot(is.na(df$report_time_limit_hours[df$record_type == "aggregate"]))
